spring:
  application:
    name: EUREKA-HA

server:
  port: 10086

---
spring:
  profiles: eureka-server1
eureka:
  instance:
    hostname: 192.168.66.103
  client:
    service-url:
      defaultZone: http://192.168.66.103:10086/eureka/,http://192.168.66.104:10086/eureka/
    fetchRegistry: 'false'
    registerWithEureka: 'false'

---
spring:
  profiles: eureka-server2
eureka:
  instance:
    hostname: 192.168.66.104
  client:
    service-url:
      defaultZone: http://192.168.66.103:10086/eureka/,http://192.168.66.104:10086/eureka/
    fetchRegistry: 'false'
    registerWithEureka: 'false'
