# 集群版
spring:
  application:
    name: EUREKA-HA

---
server:
  port: 10086
spring:
  # 指定profile=eureka-server1
  profiles:
    active: eureka-server1
eureka:
  instance:
    # 指定当profile=eureka-server1时，主机名是eureka-server1
    hostname: 192.168.66.103
    prefer-ip-address: true
  client:
    service-url:
      # 将自己注册到eureka-server1、eureka-server2这个Eureka上面去
      defaultZone: http://192.168.66.103:10086/eureka/,http://192.168.66.104:10086/eureka/
    fetch-registry: false
    register-with-eureka: false

---
server:
  port: 10086
spring:
  profiles:
    active: eureka-server2
eureka:
  instance:
    hostname: 192.168.66.104
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.66.103:10086/eureka/,http://192.168.66.104:10086/eureka/
    fetch-registry: false
    register-with-eureka: false